CREATE TABLE IF NOT EXISTS Users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username INTEGER UNIQUE NOT NULL,
    password INTEGER NOT NULL
)

CREATE TABLE IF NOT EXISTS Orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    order_time TIME NOT NULL,
    FOREIGN KEY(user_id) REFERENCES Users(id)
)

CREATE TABLE IF NOT EXISTS Order_Details (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER NOT NULL,
    order_details TEXT NOT NULL,
    FOREIGN KEY(order_id) REFERENCES Orders(id)
)